name: Node.js CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "18", "20", "22", "24", "26" ]
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run build --if-present
      - run: npm test
